spring:
  elasticsearch:
    uris: http://localhost:9200
  ai:
    openai:
      api-key: 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
      chat:
        options:
          temperature: 0.5
          user: rubenspringai
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 56875

